name: Sanitizers CI

on:
  push:
    branches:
      - main
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**/*.cpp'
      - 'tests/**/*.hpp'
      - 'tests/**/*.h'
      - 'CMakeLists.txt'
      - 'tests/**/CMakeLists.txt'
      - '.github/workflows/ci-sanitizer.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**/*.cpp'
      - 'tests/**/*.hpp'
      - 'tests/**/*.h'
      - 'CMakeLists.txt'
      - 'tests/**/CMakeLists.txt'
      - '.github/workflows/ci-sanitizer.yml'
jobs:
  sanitizers:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, thread, undefined]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install --yes -qq ninja-build clang libboost-test-dev

      - name: Configure (${{ matrix.sanitizer }} sanitizer)
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer"
          -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=${{ matrix.sanitizer }}"
          -DBUILD_UNIT_TESTS=ON
          -DBUILD_INTEGRATION_TESTS=OFF

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure